/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoprolog;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author WillianKanashiro
 */
public class TrabalhoDamas_Tabuleiro extends javax.swing.JFrame {

    private String posicaoAnterior = "";
    private String jogada = "";

    /**
     * Creates new form TrabalhoDamas_Tabuleiro
     */
    public TrabalhoDamas_Tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel5.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel7.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel10.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel14.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel16.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel16.setOpaque(true);
        jLabel16.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel17.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel17.setOpaque(true);
        jLabel17.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel18.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel20.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel20.setOpaque(true);
        jLabel20.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel22.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel22.setOpaque(true);
        jLabel22.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel23.setOpaque(true);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel24.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel24.setOpaque(true);
        jLabel24.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel26.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel26.setOpaque(true);
        jLabel26.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel27.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel27.setOpaque(true);
        jLabel27.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel28.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel28.setOpaque(true);
        jLabel28.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel29.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel29.setOpaque(true);
        jLabel29.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel30.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel30.setOpaque(true);
        jLabel30.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel31.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel31.setOpaque(true);
        jLabel31.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel32.setBackground(new java.awt.Color(0, 0, 0));
        jLabel32.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel32.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel32.setOpaque(true);
        jLabel32.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel33.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel33.setOpaque(true);
        jLabel33.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel34.setOpaque(true);
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel35.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel35.setOpaque(true);
        jLabel35.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel36.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel36.setOpaque(true);
        jLabel36.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel37.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel37.setOpaque(true);
        jLabel37.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel38.setOpaque(true);
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel39.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel39.setOpaque(true);
        jLabel39.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel40.setBackground(new java.awt.Color(0, 0, 0));
        jLabel40.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel40.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel40.setOpaque(true);
        jLabel40.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel41.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel41.setOpaque(true);
        jLabel41.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jLabel42.setBackground(new java.awt.Color(0, 0, 0));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel42.setOpaque(true);
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel43.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel43.setOpaque(true);
        jLabel43.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel44.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel44.setOpaque(true);
        jLabel44.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel45.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel45.setOpaque(true);
        jLabel45.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jLabel46.setBackground(new java.awt.Color(0, 0, 0));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel46.setOpaque(true);
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel47.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel47.setOpaque(true);
        jLabel47.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jLabel48.setBackground(new java.awt.Color(0, 0, 0));
        jLabel48.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel48.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel48.setOpaque(true);
        jLabel48.setPreferredSize(new java.awt.Dimension(80, 80));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel49.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel49.setOpaque(true);
        jLabel49.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        jLabel50.setBackground(new java.awt.Color(0, 0, 0));
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel50.setOpaque(true);
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel51.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel51.setOpaque(true);
        jLabel51.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jLabel52.setBackground(new java.awt.Color(0, 0, 0));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel52.setOpaque(true);
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel53.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel53.setOpaque(true);
        jLabel53.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        jLabel54.setBackground(new java.awt.Color(0, 0, 0));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel54.setOpaque(true);
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, -1, -1));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel55.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel55.setOpaque(true);
        jLabel55.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, -1));

        jLabel56.setBackground(new java.awt.Color(0, 0, 0));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel56.setOpaque(true);
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel57.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel57.setOpaque(true);
        jLabel57.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        jLabel58.setBackground(new java.awt.Color(0, 0, 0));
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel58.setOpaque(true);
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel59.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel59.setOpaque(true);
        jLabel59.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, -1, -1));

        jLabel60.setBackground(new java.awt.Color(0, 0, 0));
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel60.setOpaque(true);
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel61.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel61.setOpaque(true);
        jLabel61.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        jLabel62.setBackground(new java.awt.Color(0, 0, 0));
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel62.setOpaque(true);
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, -1, -1));

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel63.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel63.setOpaque(true);
        jLabel63.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));

        jLabel64.setBackground(new java.awt.Color(0, 0, 0));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        jLabel64.setOpaque(true);
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("DAMAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 141, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 142, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if ("".equals(posicaoAnterior)) {
            jLabel19.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "3/2";
            posicaoAnterior = "3/2";
            System.out.println(jogada);
        } else {
            jLabel19.setBorder(null);
            jogada += "-3/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";

        }
        
        
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        if ("".equals(posicaoAnterior)) {
            jLabel32.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "4/1";
            posicaoAnterior = "4/1";
            System.out.println(jogada);
        } else {
            jLabel32.setBorder(null);
            jogada += "-4/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";

        }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if ("".equals(posicaoAnterior)) {
            jLabel1.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "1/2";
            posicaoAnterior = "1/2";
            System.out.println(jogada);
        } else {
            jLabel1.setBorder(null);
            jogada += "-1/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if ("".equals(posicaoAnterior)) {
            jLabel4.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "1/4";
            posicaoAnterior = "1/4";
            System.out.println(jogada);
        } else {
            jLabel4.setBorder(null);
            jogada += "-1/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "1/6";
            posicaoAnterior = "1/6";
            System.out.println(jogada);
        } else {
            jogada += "-1/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "1/8";
            posicaoAnterior = "1/8";
            System.out.println(jogada);
        } else {
            jogada += "-1/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "2/1";
            posicaoAnterior = "2/1";
            System.out.println(jogada);
        } else {
            jogada += "-2/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "2/3";
            posicaoAnterior = "2/3";
            System.out.println(jogada);
        } else {
            jogada += "-2/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "2/5";
            posicaoAnterior = "2/5";
            System.out.println(jogada);
        } else {
            jogada += "-2/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "2/7";
            posicaoAnterior = "2/7";
            System.out.println(jogada);
        } else {
            jogada += "-2/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "3/4";
            posicaoAnterior = "3/4";
            System.out.println(jogada);
        } else {
            jogada += "-3/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "3/6";
            posicaoAnterior = "3/6";
            System.out.println(jogada);
        } else {
            jogada += "-3/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "3/8";
            posicaoAnterior = "3/8";
            System.out.println(jogada);
        } else {
            jogada += "-3/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "4/3";
            posicaoAnterior = "4/3";
            System.out.println(jogada);
        } else {
            jogada += "-4/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "4/5";
            posicaoAnterior = "4/5";
            System.out.println(jogada);
        } else {
            jogada += "-4/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "4/7";
            posicaoAnterior = "4/7";
            System.out.println(jogada);
        } else {
            jogada += "-4/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "5/2";
            posicaoAnterior = "5/2";
            System.out.println(jogada);
        } else {
            jogada += "-5/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "5/4";
            posicaoAnterior = "5/4";
            System.out.println(jogada);
        } else {
            jogada += "-5/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "5/6";
            posicaoAnterior = "5/6";
            System.out.println(jogada);
        } else {
            jogada += "-5/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "5/8";
            posicaoAnterior = "5/8";
            System.out.println(jogada);
        } else {
            jogada += "-5/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "6/1";
            posicaoAnterior = "6/1";
            System.out.println(jogada);
        } else {
            jogada += "-6/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "6/3";
            posicaoAnterior = "6/3";
            System.out.println(jogada);
        } else {
            jogada += "-6/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "6/5";
            posicaoAnterior = "6/5";
            System.out.println(jogada);
        } else {
            jogada += "-6/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "6/7";
            posicaoAnterior = "6/7";
            System.out.println(jogada);
        } else {
            jogada += "-6/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "7/2";
            posicaoAnterior = "7/2";
            System.out.println(jogada);
        } else {
            jogada += "-7/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "7/4";
            posicaoAnterior = "7/4";
            System.out.println(jogada);
        } else {
            jogada += "-7/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "7/6";
            posicaoAnterior = "7/6";
            System.out.println(jogada);
        } else {
            jogada += "-7/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "7/8";
            posicaoAnterior = "7/8";
            System.out.println(jogada);
        } else {
            jogada += "-7/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "8/1";
            posicaoAnterior = "8/1";
            System.out.println(jogada);
        } else {
            jogada += "-8/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "8/3";
            posicaoAnterior = "8/3";
            System.out.println(jogada);
        } else {
            jogada += "-8/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "8/5";
            posicaoAnterior = "8/5";
            System.out.println(jogada);
        } else {
            jogada += "-8/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        if ("".equals(posicaoAnterior)) {
            jogada = "8/7";
            posicaoAnterior = "8/7";
            System.out.println(jogada);
        } else {
            jogada += "-8/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_jLabel62MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabalhoDamas_Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TrabalhoDamas_Tabuleiro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
