/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoprolog;

import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author WillianKanashiro
 */
public class TrabalhoDamas_Tabuleiro extends javax.swing.JFrame {

    private String posicaoAnterior = "";
    private String jogada = "";
    private ArrayList<JLabel> casas;

    /**
     * Creates new form TrabalhoDamas_Tabuleiro
     */
    public TrabalhoDamas_Tabuleiro() {
        initComponents();
        this.casas = this.criarListaJLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        casa1_2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        casa1_4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        casa1_6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        casa1_8 = new javax.swing.JLabel();
        casa2_1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        casa2_3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        casa2_5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        casa2_7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        casa3_2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        casa3_4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        casa3_6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        casa3_8 = new javax.swing.JLabel();
        casa4_7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        casa4_5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        casa4_3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        casa4_1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        casa6_1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        casa5_2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        casa6_3 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        casa5_4 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        casa6_5 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        casa5_6 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        casa6_7 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        casa5_8 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        casa8_1 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        casa7_2 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        casa8_3 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        casa7_4 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        casa8_5 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        casa7_6 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        casa8_7 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        casa7_8 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        casa1_2.setBackground(new java.awt.Color(0, 0, 0));
        casa1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa1_2.setOpaque(true);
        casa1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa1_2MouseClicked(evt);
            }
        });
        jPanel3.add(casa1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        casa1_4.setBackground(new java.awt.Color(0, 0, 0));
        casa1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa1_4.setOpaque(true);
        casa1_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa1_4MouseClicked(evt);
            }
        });
        jPanel3.add(casa1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel5.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        casa1_6.setBackground(new java.awt.Color(0, 0, 0));
        casa1_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa1_6.setOpaque(true);
        casa1_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa1_6MouseClicked(evt);
            }
        });
        jPanel3.add(casa1_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel7.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        casa1_8.setBackground(new java.awt.Color(0, 0, 0));
        casa1_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa1_8.setOpaque(true);
        casa1_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa1_8MouseClicked(evt);
            }
        });
        jPanel3.add(casa1_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        casa2_1.setBackground(new java.awt.Color(0, 0, 0));
        casa2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa2_1.setOpaque(true);
        casa2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa2_1MouseClicked(evt);
            }
        });
        jPanel3.add(casa2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel10.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        casa2_3.setBackground(new java.awt.Color(0, 0, 0));
        casa2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa2_3.setOpaque(true);
        casa2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa2_3MouseClicked(evt);
            }
        });
        jPanel3.add(casa2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        casa2_5.setBackground(new java.awt.Color(0, 0, 0));
        casa2_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa2_5.setOpaque(true);
        casa2_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa2_5MouseClicked(evt);
            }
        });
        jPanel3.add(casa2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel14.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        casa2_7.setBackground(new java.awt.Color(0, 0, 0));
        casa2_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa2_7.setOpaque(true);
        casa2_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa2_7MouseClicked(evt);
            }
        });
        jPanel3.add(casa2_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel16.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel16.setOpaque(true);
        jLabel16.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel17.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel17.setOpaque(true);
        jLabel17.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel18.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        casa3_2.setBackground(new java.awt.Color(0, 0, 0));
        casa3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa3_2.setOpaque(true);
        casa3_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa3_2MouseClicked(evt);
            }
        });
        jPanel3.add(casa3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel20.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel20.setOpaque(true);
        jLabel20.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        casa3_4.setBackground(new java.awt.Color(0, 0, 0));
        casa3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa3_4.setOpaque(true);
        casa3_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa3_4MouseClicked(evt);
            }
        });
        jPanel3.add(casa3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel22.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel22.setOpaque(true);
        jLabel22.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        casa3_6.setBackground(new java.awt.Color(0, 0, 0));
        casa3_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa3_6.setOpaque(true);
        casa3_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa3_6MouseClicked(evt);
            }
        });
        jPanel3.add(casa3_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel24.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel24.setOpaque(true);
        jLabel24.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        casa3_8.setBackground(new java.awt.Color(0, 0, 0));
        casa3_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"))); // NOI18N
        casa3_8.setOpaque(true);
        casa3_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa3_8MouseClicked(evt);
            }
        });
        jPanel3.add(casa3_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        casa4_7.setBackground(new java.awt.Color(0, 0, 0));
        casa4_7.setMaximumSize(new java.awt.Dimension(80, 80));
        casa4_7.setMinimumSize(new java.awt.Dimension(80, 80));
        casa4_7.setOpaque(true);
        casa4_7.setPreferredSize(new java.awt.Dimension(80, 80));
        casa4_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa4_7MouseClicked(evt);
            }
        });
        jPanel3.add(casa4_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel27.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel27.setOpaque(true);
        jLabel27.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        casa4_5.setBackground(new java.awt.Color(0, 0, 0));
        casa4_5.setMaximumSize(new java.awt.Dimension(80, 80));
        casa4_5.setMinimumSize(new java.awt.Dimension(80, 80));
        casa4_5.setOpaque(true);
        casa4_5.setPreferredSize(new java.awt.Dimension(80, 80));
        casa4_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa4_5MouseClicked(evt);
            }
        });
        jPanel3.add(casa4_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel29.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel29.setOpaque(true);
        jLabel29.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        casa4_3.setBackground(new java.awt.Color(0, 0, 0));
        casa4_3.setMaximumSize(new java.awt.Dimension(80, 80));
        casa4_3.setMinimumSize(new java.awt.Dimension(80, 80));
        casa4_3.setOpaque(true);
        casa4_3.setPreferredSize(new java.awt.Dimension(80, 80));
        casa4_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa4_3MouseClicked(evt);
            }
        });
        jPanel3.add(casa4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel31.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel31.setOpaque(true);
        jLabel31.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        casa4_1.setBackground(new java.awt.Color(0, 0, 0));
        casa4_1.setMaximumSize(new java.awt.Dimension(80, 80));
        casa4_1.setMinimumSize(new java.awt.Dimension(80, 80));
        casa4_1.setOpaque(true);
        casa4_1.setPreferredSize(new java.awt.Dimension(80, 80));
        casa4_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa4_1MouseClicked(evt);
            }
        });
        jPanel3.add(casa4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel33.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel33.setOpaque(true);
        jLabel33.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        casa6_1.setBackground(new java.awt.Color(0, 0, 0));
        casa6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa6_1.setOpaque(true);
        casa6_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa6_1MouseClicked(evt);
            }
        });
        jPanel3.add(casa6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel35.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel35.setOpaque(true);
        jLabel35.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        casa5_2.setBackground(new java.awt.Color(0, 0, 0));
        casa5_2.setMaximumSize(new java.awt.Dimension(80, 80));
        casa5_2.setMinimumSize(new java.awt.Dimension(80, 80));
        casa5_2.setOpaque(true);
        casa5_2.setPreferredSize(new java.awt.Dimension(80, 80));
        casa5_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa5_2MouseClicked(evt);
            }
        });
        jPanel3.add(casa5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel37.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel37.setOpaque(true);
        jLabel37.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        casa6_3.setBackground(new java.awt.Color(0, 0, 0));
        casa6_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa6_3.setOpaque(true);
        casa6_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa6_3MouseClicked(evt);
            }
        });
        jPanel3.add(casa6_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel39.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel39.setOpaque(true);
        jLabel39.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        casa5_4.setBackground(new java.awt.Color(0, 0, 0));
        casa5_4.setMaximumSize(new java.awt.Dimension(80, 80));
        casa5_4.setMinimumSize(new java.awt.Dimension(80, 80));
        casa5_4.setOpaque(true);
        casa5_4.setPreferredSize(new java.awt.Dimension(80, 80));
        casa5_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa5_4MouseClicked(evt);
            }
        });
        jPanel3.add(casa5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel41.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel41.setOpaque(true);
        jLabel41.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        casa6_5.setBackground(new java.awt.Color(0, 0, 0));
        casa6_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa6_5.setOpaque(true);
        casa6_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa6_5MouseClicked(evt);
            }
        });
        jPanel3.add(casa6_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel43.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel43.setOpaque(true);
        jLabel43.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        casa5_6.setBackground(new java.awt.Color(0, 0, 0));
        casa5_6.setMaximumSize(new java.awt.Dimension(80, 80));
        casa5_6.setMinimumSize(new java.awt.Dimension(80, 80));
        casa5_6.setOpaque(true);
        casa5_6.setPreferredSize(new java.awt.Dimension(80, 80));
        casa5_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa5_6MouseClicked(evt);
            }
        });
        jPanel3.add(casa5_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel45.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel45.setOpaque(true);
        jLabel45.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        casa6_7.setBackground(new java.awt.Color(0, 0, 0));
        casa6_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa6_7.setOpaque(true);
        casa6_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa6_7MouseClicked(evt);
            }
        });
        jPanel3.add(casa6_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel47.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel47.setOpaque(true);
        jLabel47.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        casa5_8.setBackground(new java.awt.Color(0, 0, 0));
        casa5_8.setMaximumSize(new java.awt.Dimension(80, 80));
        casa5_8.setMinimumSize(new java.awt.Dimension(80, 80));
        casa5_8.setOpaque(true);
        casa5_8.setPreferredSize(new java.awt.Dimension(80, 80));
        casa5_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa5_8MouseClicked(evt);
            }
        });
        jPanel3.add(casa5_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel49.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel49.setOpaque(true);
        jLabel49.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        casa8_1.setBackground(new java.awt.Color(0, 0, 0));
        casa8_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa8_1.setOpaque(true);
        casa8_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa8_1MouseClicked(evt);
            }
        });
        jPanel3.add(casa8_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel51.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel51.setOpaque(true);
        jLabel51.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        casa7_2.setBackground(new java.awt.Color(0, 0, 0));
        casa7_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa7_2.setOpaque(true);
        casa7_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa7_2MouseClicked(evt);
            }
        });
        jPanel3.add(casa7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel53.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel53.setOpaque(true);
        jLabel53.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        casa8_3.setBackground(new java.awt.Color(0, 0, 0));
        casa8_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa8_3.setOpaque(true);
        casa8_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa8_3MouseClicked(evt);
            }
        });
        jPanel3.add(casa8_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, -1, -1));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel55.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel55.setOpaque(true);
        jLabel55.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, -1));

        casa7_4.setBackground(new java.awt.Color(0, 0, 0));
        casa7_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa7_4.setOpaque(true);
        casa7_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa7_4MouseClicked(evt);
            }
        });
        jPanel3.add(casa7_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel57.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel57.setOpaque(true);
        jLabel57.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        casa8_5.setBackground(new java.awt.Color(0, 0, 0));
        casa8_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa8_5.setOpaque(true);
        casa8_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa8_5MouseClicked(evt);
            }
        });
        jPanel3.add(casa8_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel59.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel59.setOpaque(true);
        jLabel59.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, -1, -1));

        casa7_6.setBackground(new java.awt.Color(0, 0, 0));
        casa7_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa7_6.setOpaque(true);
        casa7_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa7_6MouseClicked(evt);
            }
        });
        jPanel3.add(casa7_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel61.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel61.setOpaque(true);
        jLabel61.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        casa8_7.setBackground(new java.awt.Color(0, 0, 0));
        casa8_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa8_7.setOpaque(true);
        casa8_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa8_7MouseClicked(evt);
            }
        });
        jPanel3.add(casa8_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, -1, -1));

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel63.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel63.setOpaque(true);
        jLabel63.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));

        casa7_8.setBackground(new java.awt.Color(0, 0, 0));
        casa7_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"))); // NOI18N
        casa7_8.setOpaque(true);
        casa7_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casa7_8MouseClicked(evt);
            }
        });
        jPanel3.add(casa7_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        jLabel65.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("DAMAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 57, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casa3_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa3_2MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa3_2.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "3/2";
            posicaoAnterior = "3/2";
            System.out.println(jogada);
        } else {
            for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-3/2";
            System.out.println(jogada);
            // fazer jogada
            //this.colocaPecas("b(n,x,n,x,n,x,n,x,x,n,x,n,x,n,x,n,n,x,n,x,n,x,n,x,e,n,e,n,e,n,e,n,n,e,n,e,n,e,n,e,o,n,o,n,o,n,o,n,n,o,n,o,n,o,n,o,o,n,o,n,o,n,o,n).");
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";

        }


    }//GEN-LAST:event_casa3_2MouseClicked

    private void casa4_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa4_1MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa4_1.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "4/1";
            posicaoAnterior = "4/1";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-4/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";

        }
    }//GEN-LAST:event_casa4_1MouseClicked

    private void casa1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa1_2MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa1_2.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "1/2";
            posicaoAnterior = "1/2";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
             
            jogada += "-1/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa1_2MouseClicked

    private void casa1_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa1_4MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa1_4.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "1/4";
            posicaoAnterior = "1/4";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-1/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa1_4MouseClicked

    private void casa1_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa1_6MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa1_6.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "1/6";
            posicaoAnterior = "1/6";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-1/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa1_6MouseClicked

    private void casa1_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa1_8MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa1_8.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "1/8";
            posicaoAnterior = "1/8";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-1/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa1_8MouseClicked

    private void casa2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa2_1MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa2_1.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "2/1";
            posicaoAnterior = "2/1";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-2/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa2_1MouseClicked

    private void casa2_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa2_3MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa2_3.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "2/3";
            posicaoAnterior = "2/3";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-2/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa2_3MouseClicked

    private void casa2_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa2_5MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa2_5.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "2/5";
            posicaoAnterior = "2/5";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-2/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa2_5MouseClicked

    private void casa2_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa2_7MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa2_7.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "2/7";
            posicaoAnterior = "2/7";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-2/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa2_7MouseClicked

    private void casa3_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa3_4MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa3_4.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "3/4";
            posicaoAnterior = "3/4";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-3/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa3_4MouseClicked

    private void casa3_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa3_6MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa3_6.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "3/6";
            posicaoAnterior = "3/6";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-3/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa3_6MouseClicked

    private void casa3_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa3_8MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa3_8.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "3/8";
            posicaoAnterior = "3/8";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-3/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa3_8MouseClicked

    private void casa4_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa4_3MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa4_3.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "4/3";
            posicaoAnterior = "4/3";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-4/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa4_3MouseClicked

    private void casa4_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa4_5MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa4_5.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "4/5";
            posicaoAnterior = "4/5";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-4/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa4_5MouseClicked

    private void casa4_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa4_7MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa4_7.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "4/7";
            posicaoAnterior = "4/7";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-4/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa4_7MouseClicked

    private void casa5_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa5_2MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa5_2.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "5/2";
            posicaoAnterior = "5/2";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-5/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa5_2MouseClicked

    private void casa5_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa5_4MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa5_4.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "5/4";
            posicaoAnterior = "5/4";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-5/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa5_4MouseClicked

    private void casa5_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa5_6MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa5_6.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "5/6";
            posicaoAnterior = "5/6";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-5/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa5_6MouseClicked

    private void casa5_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa5_8MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa5_8.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "5/8";
            posicaoAnterior = "5/8";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-5/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa5_8MouseClicked

    private void casa6_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa6_1MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa6_1.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "6/1";
            posicaoAnterior = "6/1";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-6/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa6_1MouseClicked

    private void casa6_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa6_3MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa6_3.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "6/3";
            posicaoAnterior = "6/3";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-6/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa6_3MouseClicked

    private void casa6_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa6_5MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa6_5.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "6/5";
            posicaoAnterior = "6/5";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-6/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa6_5MouseClicked

    private void casa6_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa6_7MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa6_7.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "6/7";
            posicaoAnterior = "6/7";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-6/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa6_7MouseClicked

    private void casa7_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa7_2MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa7_2.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "7/2";
            posicaoAnterior = "7/2";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-7/2";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa7_2MouseClicked

    private void casa7_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa7_4MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa7_4.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "7/4";
            posicaoAnterior = "7/4";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-7/4";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa7_4MouseClicked

    private void casa7_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa7_6MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa7_6.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "7/6";
            posicaoAnterior = "7/6";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-7/6";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa7_6MouseClicked

    private void casa7_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa7_8MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa7_8.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "7/8";
            posicaoAnterior = "7/8";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-7/8";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa7_8MouseClicked

    private void casa8_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa8_1MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa8_1.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "8/1";
            posicaoAnterior = "8/1";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-8/1";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa8_1MouseClicked

    private void casa8_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa8_3MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa8_3.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "8/3";
            posicaoAnterior = "8/3";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-8/3";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa8_3MouseClicked

    private void casa8_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa8_5MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa8_5.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "8/5";
            posicaoAnterior = "8/5";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-8/5";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa8_5MouseClicked

    private void casa8_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casa8_7MouseClicked
        if ("".equals(posicaoAnterior)) {
            casa8_7.setBorder(BorderFactory.createLineBorder(Color.green, 3));
            jogada = "8/7";
            posicaoAnterior = "8/7";
            System.out.println(jogada);
        } else {
             for (int i = 0; i < casas.size(); i++) {
                casas.get(i).setBorder(null);
            }
            jogada += "-8/7";
            System.out.println(jogada);
            // fazer jogada
            // if jogada = sucesso
            // else tenta jogada de novo
            jogada = "";
            posicaoAnterior = "";
        }
    }//GEN-LAST:event_casa8_7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabalhoDamas_Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TrabalhoDamas_Tabuleiro().setVisible(true);
            }
        });
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casa1_2;
    private javax.swing.JLabel casa1_4;
    private javax.swing.JLabel casa1_6;
    private javax.swing.JLabel casa1_8;
    private javax.swing.JLabel casa2_1;
    private javax.swing.JLabel casa2_3;
    private javax.swing.JLabel casa2_5;
    private javax.swing.JLabel casa2_7;
    private javax.swing.JLabel casa3_2;
    private javax.swing.JLabel casa3_4;
    private javax.swing.JLabel casa3_6;
    private javax.swing.JLabel casa3_8;
    private javax.swing.JLabel casa4_1;
    private javax.swing.JLabel casa4_3;
    private javax.swing.JLabel casa4_5;
    private javax.swing.JLabel casa4_7;
    private javax.swing.JLabel casa5_2;
    private javax.swing.JLabel casa5_4;
    private javax.swing.JLabel casa5_6;
    private javax.swing.JLabel casa5_8;
    private javax.swing.JLabel casa6_1;
    private javax.swing.JLabel casa6_3;
    private javax.swing.JLabel casa6_5;
    private javax.swing.JLabel casa6_7;
    private javax.swing.JLabel casa7_2;
    private javax.swing.JLabel casa7_4;
    private javax.swing.JLabel casa7_6;
    private javax.swing.JLabel casa7_8;
    private javax.swing.JLabel casa8_1;
    private javax.swing.JLabel casa8_3;
    private javax.swing.JLabel casa8_5;
    private javax.swing.JLabel casa8_7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private ArrayList<JLabel> criarListaJLabel() {
        ArrayList<JLabel> listaJLabel = new ArrayList<>();
        listaJLabel.add(casa1_2);
        listaJLabel.add(casa1_4);
        listaJLabel.add(casa1_6);
        listaJLabel.add(casa1_8);
        listaJLabel.add(casa2_1);
        listaJLabel.add(casa2_3);
        listaJLabel.add(casa2_5);
        listaJLabel.add(casa2_7);
        listaJLabel.add(casa3_2);
        listaJLabel.add(casa3_4);
        listaJLabel.add(casa3_6);
        listaJLabel.add(casa3_8);
        listaJLabel.add(casa4_1);
        listaJLabel.add(casa4_3);
        listaJLabel.add(casa4_5);
        listaJLabel.add(casa4_7);
        listaJLabel.add(casa5_2);
        listaJLabel.add(casa5_4);
        listaJLabel.add(casa5_6);
        listaJLabel.add(casa5_8);
        listaJLabel.add(casa6_1);
        listaJLabel.add(casa6_3);
        listaJLabel.add(casa6_5);
        listaJLabel.add(casa6_7);
        listaJLabel.add(casa7_2);
        listaJLabel.add(casa7_4);
        listaJLabel.add(casa7_6);
        listaJLabel.add(casa7_8);
        listaJLabel.add(casa8_1);
        listaJLabel.add(casa8_3);
        listaJLabel.add(casa8_5);
        listaJLabel.add(casa8_7);



        return listaJLabel;
    }

    private void colocaPecas(String string) {
        char peao;
        ImageIcon pecaBranca = new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecabranca.png"));
        ImageIcon pecaAzul = new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/pecaazul.png"));
        ImageIcon damaBranca = new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/damabranca.png"));
        ImageIcon damaAzul = new javax.swing.ImageIcon(getClass().getResource("/trabalhoprolog/Imagens/damaAzul.png"));
        ImageIcon vazio = null;
        ImageIcon casa;
        ArrayList<Integer> salto = new ArrayList<Integer>();
        salto.add(4);
        salto.add(8);
        salto.add(12);
        salto.add(16);
        salto.add(18);
        salto.add(22);
        salto.add(26);
        salto.add(30);
       
        salto.add(36);
        salto.add(40);
        salto.add(44);
        salto.add(48);
        salto.add(50);
        salto.add(54);
        salto.add(58);
        salto.add(62);
        
        salto.add(68);
        salto.add(72);
        salto.add(76);
        salto.add(80);
        salto.add(82);
        salto.add(86);
        salto.add(90);
        salto.add(94);
        
        salto.add(100);
        salto.add(104);
        salto.add(108);
        salto.add(112);
        salto.add(114);
        salto.add(118);
        salto.add(122);
        salto.add(126);
        
        int posicao = 0;
        
        
        for (int i = 0; i < casas.size(); i++) {
            posicao = salto.get(i);
            peao = string.charAt(posicao);
            if(peao == 'x'){
                casa = pecaBranca;
            }else if(peao == 'o'){
                casa = pecaAzul;
            }else if(peao == 'a'){
                casa = damaBranca;
            }else if(peao == 'b' ){
                casa = damaAzul;
            }else{
                casa = vazio;
            }
            JLabel atual =  casas.get(i);
            atual.setIcon(casa);
            
            
         }
    }
}
